export enum ErrorCode {
  VALIDATION = "VALIDATION",
  EMAIL_ALREADY_IN_USE = "EMAIL_ALREADY_IN_USE",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  INVALID_RESET_PASSWORD = "INVALID_RESET_PASSWORD",
  RESOURCE_NOT_FOUND = "RESOURCE_NOT_FOUND",

  // HTTP
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  SYSTEM_CONFIG = "SYSTEM_CONFIG",
  BAD_REQUEST = "BAD_REQUEST",
}
